version: '3'
services:
  api:
    build:
      context: ./api/
    command: /usr/src/pachama/marketplace/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./api/:/usr/src/pachama/marketplace
      - /usr/src/pachama/marketplace/node_modules
    ports:
      - 3001:3001
    env_file: ./.env
    environment:
      NODE_ENV: development
  www:
    build:
      context: ./www/
    command: ['yarn', 'run', 'start']
    volumes:
      - ./www/:/usr/src/pachama/marketplace
      - /usr/src/pachama/marketplace/node_modules
    depends_on:
      - api
    ports:
      - 3000:3000
    env_file: ./.env
