version: '3'
services:
  marketplace-www:
    container_name: marketplace-www
    image: node:alpine
    volumes:
      - ./:/usr/src/pachama/marketplace-www
    working_dir: /usr/src/pachama/marketplace-www
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ['yarn', 'run', 'dev']
