apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: _APP_NAME_-_CI_ENVIRONMENT_SLUG_-deployment
spec:
  replicas: _REPLICAS_
  selector:
    matchLabels:
      app: _APP_NAME_-_CI_ENVIRONMENT_SLUG_
  # Pod template
  template:
    metadata:
      labels:
        app: _APP_NAME_-_CI_ENVIRONMENT_SLUG_
        track: _TRACK_
    spec:
      containers:
        - name: app
          image: gcr.io/_PROJECT_NAME_/_APP_NAME_:_VERSION_
          imagePullPolicy: Always
          ports:
            - containerPort: _APP_PORT_
          env:
            - name: AUTH0_CLIENT_ID
              value: _AUTH0_CLIENT_ID_
            - name: AUTH0_DOMAIN
              value: _AUTH0_DOMAIN_
            - name: AUTH0_CLIENT_SECRET
              value: _AUTH0_CLIENT_SECRET_
            - name: AUTH0_CALLBACK_URL
              value: http://_CI_ENVIRONMENT_SLUG_._APP_NAME_._MY_DOMAIN_/callback
            - name: MIXPANEL_TOKEN
              value: _MIXPANEL_TOKEN_
            - name: BASE_URL
              value: http://_CI_ENVIRONMENT_SLUG_._APP_NAME_._MY_DOMAIN_
            - name: PROD_URL
              value: _PROD_URL_
            - name: SENDGRID_SMTP_USERNAME
              value: _SENDGRID_SMTP_USERNAME_
            - name: SENDGRID_SMTP_PASSWORD
              value: _SENDGRID_SMTP_PASSWORD_
            - name: PACHAMA_SALES_MAIL
              value: sales@pachama.com
            - name: PACHAMA_MARKETPLACE_FROM
              value: Pachama Marketplace
            - name: PACHAMA_MARKETPLACE_MAIL
              value: marketplace@pachama.com
            - name: PACHAMA_LANDING_URL
              value: _PACHAMA_LANDING_URL_
